### ISSUE TITLE
Replace tstart, tend and dt by range

### ISSUE THREAD

**Issue by mschauer** [mschauer/MitosisStochasticDiffEq.jl#17]
and allow non-equidistant time grids. 

If the observation noise is small, it is a good idea to transform the time grid by
```
timechange(s, tstart=first(s), tend=last(s)) = tstart .+ (s .- tstart).*(2.0 .- (s .- tstart)/(tend-tstart))
```

**Comment by frankschae** [comment]
I added the `timechange` function to the new utils.jl file in #34 . So I think it mainly needs an example where this is shown to be useful.

**Comment by mschauer** [comment]
I think at some point we assume an equidistant grid?

**Comment by frankschae** [comment]
#38 now allows for non-equidistant grids such that `sample`, `backwardfilter`, and `forwardguiding` all work with adaptive solvers.

**Comment by mschauer** [comment]
There are some places using 

https://github.com/mschauer/MitosisStochasticDiffEq.jl/blob/f830b755485e061ffdbc55ad7f6e090fb205ccd9/src/utils.jl#L6

I thought that might not work

**Comment by frankschae** [comment]
This sets the `dt` of the solver for non-adaptive methods, however, in the case of an adaptive solver it just sets the initial `dt` which then gets modified by the error estimator.

**Comment by mschauer** [comment]
Ok, for the non-adaptive solvers, can we give them a grid instead of a `dt`?

**Comment by frankschae** [comment]
yes, that should be doable.  I think we could use the `tstops` argument to do so. For example, in `DiffEqSensitivity` it is used to force the solver to step to the checkpoints:

https://github.com/SciML/DiffEqSensitivity.jl/blob/25a5290013433bdadec776fa7b5a92f46e5a1777/src/sensitivity_interface.jl#L27

From the [docs](https://diffeq.sciml.ai/stable/basics/common_solver_opts/#Fixed-Stepsize-Usage)
> If tstops is set without dt, then the algorithm will step directly to each value in tstops

I'll later prepare a PR with a test to confirm it :)
