### ISSUE TITLE
GuidingDiffusionCache

### ISSUE THREAD

**Issue by fmeulen** [mschauer/MitosisStochasticDiffEq.jl#57]
Should the final line be as below? (the loglikelihood is always scalar valued)
```julia
function (G::GuidingDiffusionCache)(u,p,t)
  @unpack g = G

  x = @view u[1:end-1]
  dx = g(x,p,t)
  return mypack(dx, 0.0) #[dx; zero(eltype(u))]
end
```

**Comment by frankschae** [comment]
Using the `mypack` function is better, but I think we should keep `zero(eltype(u))` instead of 0.0, for example if Float32s are used in the rest of the program.
