### ISSUE TITLE
mypack with SArray

### ISSUE THREAD

**Issue by fmeulen** [mschauer/MitosisStochasticDiffEq.jl#58]
Rather than `mypack(a::SArray,c::Number) = SArray([a; c])` should be
```julia
mypack(a::SArray,c::Number) = SVector{length(a)+1}([a; c])
```
(don't know if this is efficient...)

**Comment by mschauer** [comment]
Perhaps `= SVector(a..., c)` is type stable

**Comment by fmeulen** [comment]
I think so.
